### ISSUE TITLE
(김성후 권성빈) 겜프프로젝트 과정평가용(방문기록)

### ISSUE THREAD

**Issue by GGMinwok** [kim-Eukkbi/DesignPatternShooting#1]
5/26 진행상황 살펴보고 갑니다.

**Comment by GGMinwok** [comment]
어.... 성후 성빈이 껄로 제목테스트 했더니 기록이 많이 남았네...  
작업과정 여기에 comment 하세요~

**Comment by GGMinwok** [comment]
6/8 작업내용 - 지금까지 한 것, 오늘 1-3교시에 한 것 구분해서 과정 기록 해주기!

**Comment by kim-Eukkbi** [comment]
6/8 작업내용 - 지금까지 한 것 : 배경 넣고 스크롤링 , 플레이어 움직임 , 플레이어 총알 발사 , 적 2종 구현중 , 패턴 추가중
1교시 : 성빈이와 적 패턴에 대한 논의, 일단 있는 적으로 패턴 만들어보기로 결정
2교시 : 적 패턴과 적 등장 패턴 만들어보기
3교시 : 원래 만들던 적보다 새로 만든 적한테 더 잘어울릴거 같아서 이미지와 코드 수정 그리고 추가 패턴 구현

**Comment by GGMinwok** [comment]
6/9 김성후 작업내용 확인함. commit 6/8작업 확인완료.

**Comment by GGMinwok** [comment]
6/22 - 이전주 작업내용 확인함 
일지 기록 따로는 없고 커밋으로 확인함

**Comment by GGMinwok** [comment]
마지막 확인완료
역시 일지는 따로 없고 commit으로 확인
